//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaPlayer.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song_playlist
    {
        public string Playlist_id { get; set; }
        public string song_id { get; set; }
        public string ID { get; set; }
    
        public virtual Playlist Playlist { get; set; }
        public virtual Song Song { get; set; }
    }
}
